### ISSUE TITLE
Docs on runtime requirements

### ISSUE THREAD

**Issue by sum-33-it** [alienkarma/cloudflare-kv-wrapper#1]
Nice work Machha! 

Wanted to know if it works on edge runtimes? Specifically if there's any deps on node API's? Docs on it would be great!

**Comment by alienkarma** [comment]
Hi

> Nice work Machha!

Thank you 😄

> Wanted to know if it works on edge runtimes? Specifically if there's any deps on node API's? Docs on it would be great!

I think it should work with edge runtime. There is no extra dependency on any other package and uses simple fetch under the hood.
